CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL
);

INSERT INTO users (username, password, role) VALUES
('administrator', 'LgK.fIIn4l|DB)ES', 'superior_officer'),
('ShadowPulse', '6vFZ+0/9H%ic=5V?', 'agent_base'),
('SkyRider23', 'FgN[Sss^Rq7_CDhB', 'agent_base'),
('LunaNova', '*z<bn244%~%+hnT,', 'agent_base'),
('PixelPioneer', '^Sds3G5ieDvtp*mM', 'agent_base'),
('TurboFalcon', 'pIFIG3G|3d}APt>)', 'agent_base'),
('MysticEcho', 'A~d@O&q._0N<6@3l', 'agent_base'),
('NeonVoyager', 'sz*q;2,]X/Uq=Or>', 'agent_base'),
('FrostByteX', '&n5=jU!}?6v}MG[9', 'agent_base'),
('QuantumWave', ';gyr)F5fA4L).BWX', 'agent_base'),
('BlazeStorm', '3Xd4GfS=+l{0K5k0', 'agent_base');

CREATE TABLE communications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    subject TEXT NOT NULL,
    content TEXT NOT NULL,
    role TEXT NOT NULL
);

INSERT INTO communications (subject, content, role) VALUES
('Intrusion Attempt', 'A potential intrusion was detected on the main gateway.', 'agent_base'),
('Malware Scan Report', 'A full malware scan has been completed with no threats found.', 'agent_base'),
('Firewall Alert', 'Unusual outbound traffic detected on port 443.', 'agent_base'),
('Security Patch', 'A new critical security patch has been applied successfully.', 'agent_base'),
('Incident Response', 'SOC team has initiated an incident response procedure.', 'agent_base'),
('Threat Intelligence', 'New IOC indicators have been added to the monitoring system.', 'agent_base'),
('Account Lockdown', 'User account locked after multiple failed login attempts.', 'agent_base'),
('Phishing Simulation', 'A phishing awareness campaign will start this week.', 'agent_base'),
('SOC Report', 'Daily SOC summary report is now available.', 'agent_base'),
('Breach Notification', 'Possible data breach detected on cloud instance.', 'agent_base'),
('CVE Alert', 'New critical CVE identified affecting kernel version 5.15.', 'agent_base'),
('Network Isolation', 'Affected subnet temporarily isolated for investigation.', 'agent_base'),
('SIEM Update', 'SIEM configuration updated with new correlation rules.', 'agent_base'),
('Access Review', 'Quarterly privileged access review is now open.', 'agent_base'),
('Security Training', 'Mandatory cybersecurity awareness training assigned.', 'agent_base'),
('Data Exfiltration Alert', 'Possible exfiltration attempt detected on endpoint.', 'agent_base'),
('Forensic Analysis', 'Memory dump collected for forensic investigation.', 'agent_base'),
('Zero-Day Alert', 'New zero-day vulnerability discovered affecting browsers.', 'agent_base'),
('Encryption Update', 'TLS certificates renewed for all critical services.', 'agent_base'),
('SOC Maintenance', 'Scheduled maintenance of the SOC monitoring dashboard.', 'agent_base'),
('Compromise Indicator', 'New IOC detected on workstation 12.', 'agent_base'),
('VPN Warning', 'Multiple VPN connections detected from foreign IPs.', 'agent_base'),
('Incident Closed', 'SOC incident #457 has been resolved.', 'agent_base'),
('Security Bulletin', 'Weekly security bulletin now available for review.', 'agent_base'),
('Phishing Alert', 'Suspicious email reported by multiple users.', 'agent_base'),
('Ransomware Detection', 'Possible ransomware activity detected on file server.', 'agent_base'),
('Security Policy Update', 'New password policy requirements implemented.', 'agent_base'),
('Threat Containment', 'Infected host quarantined successfully.', 'agent_base'),
('Audit Log', 'All system audit logs archived to secure storage.', 'agent_base'),
('Endpoint Protection', 'Endpoint security agent updated successfully.', 'agent_base'),
('Vulnerability Scan', 'Scheduled vulnerability scan completed.', 'agent_base'),
('Password Rotation', 'Admin password rotation completed as per policy.', 'agent_base'),
('Intrusion Prevention', 'IPS successfully blocked suspicious payload.', 'agent_base'),
('Security Dashboard', 'SOC dashboard metrics refreshed and optimized.', 'agent_base'),
('Anomaly Detection', 'Unusual activity detected on database server.', 'agent_base'),
('SOC Alert', 'High-severity SOC alert generated for subnet A.', 'agent_base'),
('User Compromise', 'User credentials possibly compromised on remote login.', 'agent_base'),
('Access Control', 'New MFA policy enforced for all remote logins.', 'agent_base'),
('Policy Violation', 'Unauthorized file transfer detected to external domain.', 'agent_base'),
('Security Audit', 'Annual security audit scheduled for next week.', 'agent_base'),
('Patch Advisory', 'Microsoft has released a new security advisory.', 'agent_base'),
('Data Classification', 'Sensitive files identified and tagged automatically.', 'agent_base'),
('Threat Mitigation', 'Mitigation measures applied to contain the threat.', 'agent_base'),
('SIEM Correlation', 'New SIEM correlation rules deployed successfully.', 'agent_base'),
('Suspicious File', 'Potentially malicious file quarantined.', 'agent_base'),
('SOC Escalation', 'Incident escalated to Tier 3 for investigation.', 'agent_base'),
('Risk Assessment', 'Updated risk assessment report is available.', 'agent_base'),
('SOC Notification', 'SOC monitoring resumed after brief downtime.', 'agent_base'),
('Malware Alert', 'New malware signature detected in inbound traffic.', 'agent_base'),
('Firewall Update', 'Firewall configuration updated for improved security.', 'agent_base'),
('System Upgrade', 'Core servers upgraded to the latest OS version.', 'agent_base'),
('Network Maintenance', 'Scheduled network maintenance this Sunday.', 'agent_base'),
('User Onboarding', 'New employee onboarding process initiated.', 'agent_base'),
('Database Backup', 'Daily database backup completed successfully.', 'agent_base'),
('Server Restart', 'Application server restarted due to performance issue.', 'agent_base'),
('Helpdesk Ticket', 'New helpdesk ticket assigned to your queue.', 'agent_base'),
('Software Deployment', 'New version of internal software deployed.', 'agent_base'),
('Printer Issue', 'Printer connectivity issue resolved.', 'agent_base'),
('Email Configuration', 'Email forwarding rule has been updated.', 'agent_base'),
('VPN Access', 'VPN credentials have been generated for remote work.', 'agent_base'),
('Performance Report', 'Monthly IT performance report is ready.', 'agent_base'),
('Cloud Migration', 'Cloud migration completed for storage services.', 'agent_base'),
('Hardware Request', 'New laptop request submitted for approval.', 'agent_base'),
('Network Expansion', 'Additional network nodes added to campus LAN.', 'agent_base'),
('Data Sync', 'Data synchronization completed successfully.', 'agent_base'),
('Application Error', 'Unexpected error reported in web application.', 'agent_base'),
('System Monitoring', 'Monitoring agents deployed to new hosts.', 'agent_base'),
('IT Policy', 'Updated IT usage policy is now available.', 'agent_base'),
('Scheduled Reboot', 'Servers will reboot automatically at 2 AM.', 'agent_base'),
('Change Request', 'Your change request #205 has been approved.', 'agent_base'),
('Software License', 'License for design software renewed successfully.', 'agent_base'),
('Backup Verification', 'Backup integrity check passed with no errors.', 'agent_base'),
('Storage Alert', 'Disk usage has reached 90% capacity.', 'agent_base'),
('Update Notification', 'New software updates are ready to install.', 'agent_base'),
('Access Request', 'Access granted to shared resource folder.', 'agent_base'),
('Maintenance Completed', 'Planned maintenance finished ahead of schedule.', 'agent_base'),
('IT Announcement', 'New IT support portal available to all employees.', 'agent_base'),
('Hardware Upgrade', 'RAM upgraded on main database server.', 'agent_base'),
('Application Update', 'CRM application updated to version 3.2.', 'agent_base'),
('Login Assistance', 'Password reset instructions sent to your email.', 'agent_base'),
('Network Issue', 'Temporary network outage resolved.', 'agent_base'),
('Helpdesk Feedback', 'Please rate your recent support experience.', 'agent_base'),
('User Profile Updated', 'Your user profile details were updated successfully.', 'agent_base'),
('Disk Replacement', 'Faulty disk replaced in RAID array.', 'agent_base'),
('Email Migration', 'Email migration completed successfully.', 'agent_base'),
('Printer Setup', 'New office printer configured and available.', 'agent_base'),
('Remote Support', 'IT technician connected to your system for assistance.', 'agent_base'),
('Patch Deployment', 'Latest patches deployed to all production servers.', 'agent_base'),
('Performance Optimization', 'Database queries optimized for faster response.', 'agent_base'),
('Service Request', 'Your IT service request has been processed.', 'agent_base'),
('Outage Notice', 'Unexpected outage on authentication service.', 'agent_base'),
('Configuration Change', 'Network configuration updated successfully.', 'agent_base'),
('User Access Revoked', 'Access revoked for inactive user accounts.', 'agent_base'),
('Cloud Service Alert', 'Latency detected in external cloud service.', 'agent_base'),
('Upgrade Notification', 'New version of collaboration tool available.', 'agent_base'),
('Ticket Closed', 'Your IT ticket has been resolved.', 'agent_base'),
('Device Registration', 'New mobile device registered in the system.', 'agent_base'),
('Backup Alert', 'Backup job failed on secondary node.', 'agent_base'),
('Data Restore', 'Requested data restore completed successfully.', 'agent_base'),
('Software Rollback', 'Rollback performed due to deployment issue.', 'agent_base'),
('Team Meeting Invitation', 'You are invited to the weekly team meeting scheduled for Monday at 10 AM.', 'agent_base'),
('Webinar Invitation', 'Join our upcoming webinar on cybersecurity trends this Friday.', 'agent_base'),
('Event Registration', 'Register now for the annual IT Security Summit 2025.', 'agent_base'),
('Project Kickoff Meeting', 'The project kickoff meeting will take place tomorrow at 3 PM in Conference Room B.', 'agent_base'),
('Workshop Invitation', 'You are invited to attend the hands-on cloud infrastructure workshop next week.', 'agent_base'),
('Security Briefing', 'Mandatory security briefing scheduled for all staff this Wednesday at 2 PM.', 'agent_base'),
('Team Building Event', 'Join us for a team building event this Saturday at the local park.', 'agent_base'),
('Product Launch Event', 'You are invited to the exclusive product launch event next Thursday evening.', 'agent_base'),
('Networking Event', 'Attend the industry networking event this Friday at 6 PM downtown.', 'agent_base'),
('Training Session', 'Sign up for the advanced cybersecurity training session next Monday.', 'agent_base'),
('Holiday Party', 'You are invited to the annual holiday party on December 20th at 7 PM.', 'agent_base'),
('Client Meeting', 'Reminder: Client meeting scheduled for tomorrow at 11 AM in Meeting Room 1.', 'agent_base'),
('Board Meeting', 'The quarterly board meeting will be held next Tuesday at 9 AM.', 'agent_base'),
('Strategy Session', 'Join us for a strategy planning session this Friday at 4 PM.', 'agent_base'),
('Feedback Request', 'Please provide your feedback on the recent IT changes by end of day Friday.', 'agent_base'),
('Survey Invitation', 'Participate in our employee satisfaction survey by next week.', 'agent_base'),
('Town Hall Meeting', 'All hands town hall meeting scheduled for next Wednesday at 3 PM.', 'agent_base'),
('Innovation Workshop', 'You are invited to the innovation workshop next Thursday at 10 AM.', 'agent_base'),
('Leadership Training', 'Sign up for the leadership development training starting next month.', 'agent_base'),
('Annual Review Meeting', 'Your annual performance review meeting is scheduled for next Friday at 2 PM.', 'agent_base'),
('Community Service Event', 'Join us for a community service event this Saturday morning.', 'agent_base'),
('Fundraising Gala', 'You are invited to the charity fundraising gala next Saturday evening.', 'agent_base'),
('Tech Talk Invitation', 'Attend our upcoming tech talk on emerging technologies this Thursday at noon.', 'agent_base'),
('Mentorship Program Kickoff', 'Mentorship program kickoff event scheduled for next Monday at 5 PM.', 'agent_base'),
('Wellness Workshop', 'Join us for a wellness workshop focusing on stress management next Wednesday.', 'agent_base'),
('Cultural Event', 'You are invited to the cultural appreciation event this Friday evening.', 'agent_base'),
('Hackathon Invitation', 'Participate in our internal hackathon event next weekend.', 'agent_base'),
('Secret Meeting', 'You are invited to a secret meeting for Superior Officers only. Details will be shared upon RSVP.', 'superior_officer'),
('Confidential Briefing', 'A confidential briefing session is scheduled for Senior Agents this Thursday at 1 PM.', 'superior_officer'),
('Exclusive Event', 'Invitation to an exclusive event for Senior Agents only. Please confirm your attendance.', 'superior_officer'),
('Senior Agent Workshop', 'Join the Senior Agent workshop on advanced tactics next Tuesday at 10 AM.', 'superior_officer'),
('Leadership Summit', 'You are invited to the annual Leadership Summit for Senior Agents next month.', 'superior_officer'),
('Strategic Planning Meeting', 'Senior Agents are requested to attend the strategic planning meeting this Friday at 3 PM.', 'superior_officer'),
('High-Level Briefing', 'A high-level briefing for Senior Agents is scheduled for next Wednesday at 11 AM.', 'superior_officer'),
('Top Secret Event', 'Invitation to a top secret event for Senior Agents only. Location details will be provided upon RSVP.', 'superior_officer'),
('Senior Agent Training', 'Mandatory training session for all Senior Agents next Monday at 9 AM.', 'superior_officer'),
('Elite Networking Event', 'You are invited to an elite networking event for Senior Agents this Saturday evening.', 'superior_officer'),
('Classified Meeting', 'A classified meeting for Senior Agents is scheduled for next Thursday at 2 PM.', 'superior_officer'),
('Senior Agent Conference', 'Invitation to the annual Senior Agent conference next month. Please register your attendance.', 'superior_officer'),
('Restricted Access Briefing', 'Senior Agents only: A restricted access briefing will take place this Tuesday at 4 PM.', 'superior_officer'),
('Confidential Strategy Session', 'Join the confidential strategy session for Senior Agents this Friday at 1 PM.', 'superior_officer'),
('VIP Event Invitation', 'You are invited to a VIP event exclusively for Senior Agents. Details will follow upon RSVP.', 'superior_officer'),
('Senior Agent Symposium', 'Invitation to the Senior Agent symposium on emerging threats next week.', 'superior_officer'),
('High-Level Strategy Meeting', 'Senior Agents are requested to attend the high-level strategy meeting this Wednesday at 10 AM.', 'superior_officer'),
('INV_EVENT_F1E2D3C4B5A697887766554433221100_16OCT2025_CONF_ROOM_B', 'The confidential meeting will take place in the Conference Room B at headquarter on December 2, 2025, at 09:30 AM. The session will review recent security incidents and evaluate the effectiveness of the incident response procedures. Classified information: access restricted to Superior Officers with Access Code @@FLAG@@', 'superior_officer'),
('System Maintenance Notice', 'The system will undergo scheduled maintenance on October 20, 2025, from 02:00 to 05:00 AM.', 'admin'),
('Policy Update', 'The IT security policy has been updated. Please review the changes at your earliest convenience.', 'admin'),
('New Feature Deployment', 'The new dashboard feature has been deployed successfully. Check it out in your workspace.', 'admin'),
('User Onboarding Completed', 'New users have been onboarded successfully. All accounts are active and ready to use.', 'admin'),
('Security Training Assigned', 'Mandatory cybersecurity awareness training has been assigned to all employees.', 'admin'),
('Quarterly Report', 'The IT department quarterly performance report is now available for review.', 'admin'),
('Password Policy Change', 'Password requirements have been updated. Ensure your credentials meet the new criteria.', 'admin'),
('Network Upgrade Scheduled', 'Network infrastructure will be upgraded this Friday from 10:00 PM to 02:00 AM.', 'admin'),
('System Alert', 'High CPU usage detected on server Alpha-3. Please investigate.', 'admin'),
('Backup Confirmation', 'Daily backups completed successfully for all critical systems.', 'admin'),
('Access Rights Updated', 'User permissions for the shared folder have been updated.', 'administrator'),
('Database Migration Completed', 'The database migration to the new server has been successfully completed.', 'administrator'),
('New Policy Reminder', 'Please remember to comply with the updated IT security policy.', 'administrator'),
('Software License Renewal', 'All licenses for the productivity suite have been renewed for another year.', 'administrator'),
('Incident Report', 'A minor network outage occurred yesterday. Full incident report attached.', 'administrator'),
('System Health Check', 'Routine system health check completed with no issues found.', 'administrator'),
('Patch Deployment Completed', 'All scheduled patches have been deployed successfully to production servers.', 'administrator'),
('IT Meeting Scheduled', 'A departmental IT meeting has been scheduled for next Monday at 10:00 AM.', 'administrator'),
('Remote Access Enabled', 'Remote access for new employees has been configured and tested.', 'administrator'),
('Maintenance Reminder', 'Reminder: Servers will undergo routine maintenance this weekend.', 'administrator'),
('Flag', 'Nice try!! But it is not here :(', 'superior_officer'),
('Flag', 'Nice try!! But it is not here :(', 'admin'),
('Flag', 'Nice try!! But it is not here :(', 'administrator'),
('WPCTF', 'All that is Gold Does Not Glitter.', 'superior_officer'),
('WPCTF', 'All that is Gold Does Not Glitter.', 'admin'),
('WPCTF', 'All that is Gold Does Not Glitter.', 'administrator');

CREATE TABLE flags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    value TEXT NOT NULL
);

INSERT INTO flags (value) VALUES
('Flag? What flag? :) Congrats! You found... nothing.');
